export const CART = {
  ADD_CART_PRODUCT: "ADD_CART_PRODUCT",
  REMOVE_ALL_PRODUCT: "REMOVE_ALL_PRODUCT",
  REMOVE_CART_PRODUCT: "REMOVE_CART_PRODUCT",
}

export const FAVORITE = {
  ADD_FAVORITE_PRODUCT: "ADD_FAVORITE_PRODUCT",
  REMOVE_FAVORITE_PRODUCT: "REMOVE_FAVORITE_PRODUCT",
}

export const FIRST_OPENED = {
  OPEN_FIRST_MODAL: "OPEN_FIRST_MODAL",
  CLOSE_FIRST_MODAL: "CLOSE_FIRST_MODAL",
}

export const SECOND_OPENED = {
  OPEN_SECOND_MODAL: "OPEN_SECOND_MODAL",
  CLOSE_SECOND_MODAL: "CLOSE_SECOND_MODAL",
}

export const CARD_DATA = {
  ADD_DATA: "ADD_DATA"
}

export const PRODUCTS = {
  GET_PRODUCTS: "GET_PRODUCTS"
}

export const CATEGORIES = {
  GET_CATEGORIES: "GET_CATEGORIES"
}