export const CASH = {
  ADD_CASH: "ADD_CASH",
  GET_CASH: "GET_CASH"
}

export const CUSTOMER ={
  ADD_MANY_CUSTOMERS: "ADD_MANY_CUSTOMERS",
  ADD_CUSTOMER: "ADD_CUSTOMER",
  REMOVE_CUSTOMER: "REMOVE_CUSTOMER"
}